version: '3.6'
networks:
  mongo-net:
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
  zoonav:
    image: elkozmon/zoonavigator
    restart: always
    hostname: zoonav
    ports:
      - 9000:9000
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  mongodb:
    image: md03/mongo-replica
    ports:
      - "27017:27017"
    restart: always
    networks:
      - mongo-net
