version: '3.6'
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
  zoonav:
    image: elkozmon/zoonavigator
    restart: always
    hostname: zoonav
    ports:
      - 9000:9000

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    