version: '3.6'
networks:
  mongo-net:
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
  zoonav:
    image: elkozmon/zoonavigator
    restart: always
    hostname: zoonav
    ports:
      - 9000:9000
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  mongo1:
    hostname: localhost # This is a only way to make it accessible from host. I could use network_mode: host, but it's working only on Linux hosts
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always
    networks:
      - mongo-net
    entrypoint: [
      '/bin/sh',
      '-c',
      '/mongo-rs.sh'
    ]
    volumes:
      - ./scripts/mongo-rs.sh:/mongo-rs.sh
