version: '3.6'
services:
  gateway:
    image: openresty/openresty:alpine
    network_mode: host
    restart: always
    volumes:
      - ./gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gateway/conf.d:/etc/nginx/conf.d
    #depends_on:
      #- app
  #app:
    #build:
      #context: ./http
    #network_mode: host
      