# test docker compose config. Not intended for production or development:
version: '3.6'

services:
  main-db-test:
    image: postgres:alpine
    volumes:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    ports:
      - "5431:5432"

  stats-db-test:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    ports:
      - "8122:8123"
      - "19001:9000"

  in-memory-test:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6378:6379"

  zookeeper-test:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2180:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-test:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    restart: unless-stopped
    ports:
      - '9091:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9090,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
