# test docker compose config. Not intended for production or development:
version: '3.6'

services:
  main-db-test:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    ports:
      - "5431:5432"

  stats-db-test:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    ports:
      - "8122:8123"
      - "19001:9000"

  in-memory-test:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6378:6379"

  zookeeper-test:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper-test
    restart: unless-stopped
    ports:
      - "2180:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
