# development docker compose config. Not intended for production:
version: '3.6'

services:
  main-db:
    image: postgres:alpine
    restart: always
    volumes:
       - db_volume:/data/postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  stats-db:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
      - "8123:8123"
      - "19000:9000"

  in-memory:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  zoonav:
    image: elkozmon/zoonavigator
    restart: always
    hostname: zoonav
    ports:
      - "9000:9000"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  db_volume:
