name: testing-api
on: 
  push:
    paths: 
      - 'apps/api/**'
      
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
        
      - name: Run docker-compose
        run: docker compose up -d
        
      - name: Wait for databases
        run: sleep 30
        
      - name: Install packages with pnpm
        run: pnpm install --frozen-lockfile
        
      - name: Run unit tests
        run: pnpm test

      - name: [DEBUG] Show docker compose logs
        run: docker compose logs
        
      - name: Run e2e tests
        run: pnpm test:e2e
        
      - name: Close docker-compose
        run: docker compose down -v
